# A version of the BBDM environment setup with accessible mirrors.
# See: https://github.com/xuekt98/BBDM/blob/main/environment.yml
name: BBDM
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - numpy=1.24.2
  - scipy=1.9.1
  - scikit-image=0.20.0
  - scikit-learn=1.2.1
  - matplotlib
  - pillow=9.4.0
  - tqdm
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip:
    - absl-py
    - albumentations==1.3.0
    - einops
    - imageio
    - lightning-utilities==0.7.1
    - lpips==0.1.4
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - pytorch-lightning==1.9.3
    - tensorboard
    - transformers==4.26.1
    - torchsummary